<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/11/12 13:31:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=oasis-ems;host=localhost',
  'profiler' => false,
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
