<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/12 19:50:53
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
