<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/12 22:56:35
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
