<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/11/13 09:29:00
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
