<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/13 09:42:22
sfConfig::add(array(
  'mod_ticketsreports_enabled' => true,
  'mod_ticketsreports_view_class' => 'sfPHP',
));
