<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/12 19:58:46
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
