<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/12 07:32:59
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
